### ISSUE TITLE
website

### ISSUE THREAD

**Issue by clarknelson** [sushijs/sushijs.github.io#5]
I'd like to develop this website :) 

I'm a front-end developer who streams in my freetime at livecoding.tv. This would make for a really fun stream and I don't believe it will take too long or be very challenging.

I have a good amount of experience with Jekyll which would be a great platform so we can deploy on github pages.

Just let me know what you're thinking and if I can help out :)
- Clark

**Comment by clarknelson** [comment]
Lol there already is a website, what was I thinking in 2015!

**Comment by terinjokes** [comment]
Furthermore, you opened this in the repo for the website. 🤷‍♂️

**Comment by clarknelson** [comment]
2019 me has noticed xD, 2015 me had no clue
